version: "3"

services:
  auth:
    build:
      context: ./authservice
    volumes:
      - ./authservice/config.sample.json:/app/config.json
    ports:
      - 9000:9000
    networks:
      - public
      - auth-network
    restart: always

  auth-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=auth
    networks:
      - auth-network
    restart: always

  chat:
    build:
      context: ./chat
    volumes:
      - ./chat/config.sample.yaml:/app/config.yaml
    ports:
      - 9001:9001
    networks:
      - public
      - chat-network
    restart: always

networks:
  public:
  auth-network:
  chat-network:
