apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - port: 9000
      targetPort: grpc
      name: grpc
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      volumes:
        - name: auth-config-vm
          configMap:
            name: auth-config-map
            items:
              - key: config.sample.json
                path: config.json
      containers:
        - name: auth
          image: auth
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
              name: grpc
          volumeMounts:
            - name: auth-config-vm
              mountPath: /app/config.json
              subPath: config.json
