# Check https://github.com/go-task/task for how to install.
version: "3"

tasks:
  protoc:
    cmds:
      - >
        protoc
        protos/authservice/authservice.proto
        protos/authservice/user.proto
        --go_out=plugins=grpc:.
        --go_opt=paths=source_relative
